# Declare variables to be passed into your templates.


# Deployment Settings 
# CURRENTLY MUST BE RUN AS PRIVILEGED

Deployment:
  Name: hicn-k8s-test
  Image: cbmckni/hicn-client 
  Host: false # deploy to specific host vs "random"
  Hostname: epic001.clemson.edu
  Replicas: 1
  Arg: "tail -f /dev/null"
# EXAMPLE MANUAL: "tail -f /dev/null" 

# Resource Requests

Resources:
  Requests:
    CPU: 1
    Memory: 4Gi
  Limits:
    CPU: 1
    Memory: 4Gi



# PVC Settings

ExistingPVC:
  # If true, use existing PVC on local cluster.
  Enabled: true
  Name: deepgtex-prp
  Path: /workspace

NewPVC:
  # If true, create new PVC on local cluster.
  Enabled: false
  Name: hicn-k8s-pvc-test
  Size: 50Gi
  StorageClass: nfs # Make sure storage class provisioner exists!
  Path: /workspace



# Ingress control settings
Ingress:
  Enabled: false
  # The subdomain to associate with this service.
  Host: hicnlakev1.nautilus.optiputer.net
  # The class of the ingress controller to use.
  Class: traefik

